### ISSUE TITLE
tools/flavor-name-check.py: Read list of mandatory flavors from external YAML

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#162]
https://github.com/SovereignCloudStack/Docs/blob/6b21dabe2833c3db979cba4eb9513393a0001bbe/Design-Docs/tools/flavor-name-check.py#L32
should be changed to read the list of mandatory flavors from an external YAML file, once we have it implemented.
See https://github.com/SovereignCloudStack/issues/issues/235

**Comment by fkr** [comment]
https://github.com/SovereignCloudStack/Docs/pull/183

**Comment by tibeer** [comment]
Relates SovereignCloudStack/issues#236

**Comment by garloff** [comment]
This has been implemented via #183.
