### ISSUE TITLE
Existing SCS Clouds link is dead

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/standards#209]
Found in <https://github.com/SovereignCloudStack/standards#existing-scs-clouds>:
(...)
The SCS Community partners (PlusServer, Wavecon, etc.) are providing pro-bono resources to further the development of the Project. The resources provided can be found [here](https://github.com/SovereignCloudStack/standards/blob/main/Contributor-Docs/partners/cloud-resources.md).
(...)
The link from "here" is dead. Should lead to <https://github.com/SovereignCloudStack/docs-page/blob/main/community/contribute/cloud-resources/cloud-resources.md> OR <https://github.com/SovereignCloudStack/docs/blob/main/community/contribute/cloud-resources/cloud-resources.md>. Unsure which documentation is now the right one.

**Comment by itrich** [comment]
I'm currently reworking the `community` folder in the `docs` repository and will fix the broken link once the corresponding PR https://github.com/SovereignCloudStack/docs/pull/5 is merged.

**Comment by frosty-geek** [comment]
ref #211
