### ISSUE TITLE
Re-evaluate types of existing records: "Decision Record" or "Standard"?

### ISSUE THREAD

**Issue by joshmue** [SovereignCloudStack/standards#233]
There are some "Decision Records" which looked like "Standards" to me.

Verify and open up a cleanup PR, if necessary.

**Comment by joshmue** [comment]
#240 fixes this document's location only.
#241 fixes (IMHO) this document's type and location.
#242 adds a template in `Standards/` like it already exists for `Decisions`.

Having another look at things, I found that AFAIU, the current structure actually violates [SCS-0001](https://github.com/SovereignCloudStack/standards/blob/13b0df8f452ab565628a1abf677d76e91282e497/Standards/scs-0001-v1-sovereign-cloud-standards.md), which says:

> The pull request MUST add exactly one SCS document, in the Standards folder.

So, bringing up the open question of [SCS-0002](https://github.com/SovereignCloudStack/standards/blob/13b0df8f452ab565628a1abf677d76e91282e497/Decisions/scs-0002-v1-standards-docs-org.md) again...

> We don't know yet whether there is always a clear distinction between Standards and Decisions (ADRs) -- if this turns out too hard to decide, we may unify those two directories. (The decision will still be needed and be reflected in the header, but finding the docs will be easier.)

Question: Follow SCS-0001 by putting all files into a single directory or change SCS-0001 to reflect the de-facto presence of multiple directories?
If doing the former, all linked PR's I just created (except partly #241) can be just closed.

@garloff @horazont @itrich Opinions?

**Comment by garloff** [comment]
Having them all in the Standards/ folder looks good to me.

**Comment by joshmue** [comment]
Only `status-page-comparison` remains to be moved, but that is not scope of this issue. Hence, I'm closing it.
