### ISSUE TITLE
SCS flavors suggestion 2: IaC tool support for discoverability

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#273]
https://input.scs.community/Why-Standardized-Flavors-And-Names?view#Suggestion-2

**Comment by artificial-intelligence** [comment]
imho we should at least specify which IaC tools we do support, there are a ton and we might need to focus on market leaders, or best tech available or some other - in the best case - objective criteria.

I'd suggest to focus on terraform as the market leader.
