### ISSUE TITLE
Entropy test sets up and tears down its network topology

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#317]
Currently, we have three active versions of the certification set _SCS-compatible IaaS_, mainly because we issued a new version purely for the new flavor naming V3. The goal should be to issue new versions less frequently, with some advance notice, and maybe with more significant changes. Let's collect our ideas for V4 here before we issue it. (Work is in progress over at https://github.com/SovereignCloudStack/issues/issues/343 about better documentation of this whole process.)

Definition of done:
- [ ] set a date for stabilization of upcoming certification set V4
- [ ] collect new standards and tests that should be added

**Comment by mbuechse** [comment]
For starters, once we can [run the conformance test using Zuul](https://github.com/SovereignCloudStack/standards/issues/316), we should tentatively add `scs-0101-entropy` (with the corresponding test).

**Comment by mbuechse** [comment]
Similarly, once the [test for the interoperability guidelines](https://github.com/SovereignCloudStack/standards/issues/300) is ready, we might add it too.

**Comment by fkr** [comment]
pinging @frosty-geek to table "flavor-names for dinner"

**Comment by garloff** [comment]
Let's see what our set of IaaS standards for R5 (v6.0.0) will be and indeed align the next certification set for IaaS (and for Containers) with the release.
My suggestion would be to stabilize standards for R5 no later than Sep 1 and then have a transition period until the end of Oct. (This means that official testing against the R5 standards can be done a few weeks before the final R5 is released. This is relevant e.g. for gx-scs, which may be upgraded to R5-release candidates and which we of course expect to be fully compliant with scs-compatible.)

@mbuechse @fkr:
Do you intend to link all standards that we are working on here, so we have a target list where we expect most (if not all) of them to make it into the certification requirement set?

**Comment by mbuechse** [comment]
@garloff I think we could also use the testing yaml file to prepare the next certification version.

**Comment by fkr** [comment]
It would be good to finalize this before R5.
