### ISSUE TITLE
CI tests for mandatory-flavor-list (#319)

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#339]
With PR #319, we move away from the compressed form of listing mandatory and recommended SCS flavors to a more verbose format. While the compressed form only used SCS names and derived all properties from them, the new format lists all the properties, including the name as name and then also as extra_spec `scs:name-v1` and `scs:name-v2`.
https://github.com/SovereignCloudStack/standards/blob/issue/267/Tests/iaas/scs-0103-v1-flavors.yaml
This is more easy to read and also makes us less dependent on the names.
However, we have the same information twice now, once implicit in the name and once as explicit properties.
The risk is to have these diverge, creating inconsistencies that are embarassing for us and painful for operators and their customers. We need to avoid this.
TASKS:
- [ ] Use the existing code base to create a check for the consistency of scs-0103-v1-flavors.yaml file
- [ ] Run this code as a CI check, so we never merge a broken 0103-flavors file.

**Comment by mbuechse** [comment]
First of all, I'm not sure if the list of mandatory flavors will change very much. @frosty-geek already told me he didn't want that to happen at all.

Besides, if the list did change, we would make sure that the reference implementation wouldn't lose its certification. Which should preclude the divergence between name and properties, as long as the tests for scs-0001 check that the properties match the name. To this end, it SHOULD be extended to check the `extra_specs`. I think this would be much more pressing than the CI check.
