### ISSUE TITLE
flavor-manager-input.py uses strings instead of real types for default values

### ISSUE THREAD

**Issue by gndrmnn** [SovereignCloudStack/standards#340]
Currently, the ``flavor-manager-input.py`` produces yaml files which contain strings instead of booleans for certain default values. Namely ``public`` and ``disabled``:
https://github.com/SovereignCloudStack/standards/blob/92b3e8cc85cfff4c424bee722961609103bf4ece/Tests/iaas/flavor-naming/flavor-manager-input.py#L41-L49

We are currently working on unifying the type parsing for the osism-flavor-manager and have encountered the problem, that the yaml file in this repo (``SCS-Spec.MandatoryFlavors.verbose.yaml``), which will be automatically downloaded by the osism-flavor-manager at the users discretion, contains strings instead of booleans because of the python script mentioned above:
https://github.com/SovereignCloudStack/standards/blob/92b3e8cc85cfff4c424bee722961609103bf4ece/Tests/iaas/SCS-Spec.MandatoryFlavors.verbose.yaml#L1-L13

We propose changing the ``flavor-manager-input.py`` in this repo and regenerating the yaml file with correctly typed values.

For reference, this is how the osism flavor.yaml file looks like: https://raw.githubusercontent.com/osism/openstack-flavor-manager/main/flavors.yaml

**Comment by mbuechse** [comment]
@gndrmnn I stumbled upon this issue by coincidence. It would have been good to either assign it to me directly or to mention it in the Team IaaS meeting. At any rate, I will get to work on this soon.

**Comment by gndrmnn** [comment]
> @gndrmnn I stumbled upon this issue by coincidence. It would have been good to either assign it to me directly or to mention it in the Team IaaS meeting. At any rate, I will get to work on this soon.

Noted, I dont know the procedures just yet :)
