### ISSUE TITLE
Rename certificate type in scs-0003

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#347]
According to [scs-0003-v1-sovereign-cloud-standards-yaml.md](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0003-v1-sovereign-cloud-standards-yaml.md) SCS supports two dimensions with respect to certification:

1. _certification level_, of which there are three:
   - SCS-compatible
   - SCS-open
   - SCS-sovereign
2. _cloud layer_, of which there are two:
   - infastructure as a service (IaaS)
   - Kubernetes as a service (KaaS)

A question came up: how do we call the combination of level and cloud layer. There are the following candidates:

- certificate type
- certificate subject
- certificate topic
- certificate scope

**edit** We used this issue to find the new name, and it is now **certificate scope**. Now scs-0003 has to be adapted accordingly.

**Comment by garloff** [comment]
"certificate scope" it is according to the team's meeting.
"Scope" suggest a broader meaning than "type", so it's slightly better.

**Comment by mbuechse** [comment]
I will hijack and use this issue for the necessary change of scs-0003. I guess the change of the docs can happen within https://github.com/SovereignCloudStack/docs/pull/76.
