### ISSUE TITLE
[Standardization] GPU naming convention needs further refinements

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#366]
GPU name in [SCS Flavor Naming Standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#optional-gpu-support) need further refinement. The following aspects are described insufficiently:   

- [x] GPU capabilities are added to flavor name as extension. See [Complete Proposal for systematic flavor naming](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#complete-proposal-for-systematic-flavor-naming). However, the order of extensions is unclear. As there are three extensions currently, I would make sense and facilitate parsing/mapping if extensions have a dedicated order.
- [x] GPU naming supports suffix `h`, which can be set multiple times indicating a high-performance GPU. However "high-performance" is neither explained in detail, nor there is a mapping from `h`, `hh`, `hhh`... to measure a GPU properly as it is done for [CPU Frequency](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#frequency-suffixes)`. In favor of comparison and interoperability, standard for GPU naming SHOULD be very strict and clear here.
- [x] There are no examples provided for flavor naming with GPU support, as is is done for [CPU]() or [Memory](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#examples-5)
- [x] #375
- [x] According to SCS flavor naming, GPU generation, such as Ampere or Hopper for Nvidia, can be defined by adding appropriate suffix to GPU definition. IMO, placing generation is not sufficient as there is a huge performance difference between A10 and A100, both GPUs of generation "Ampere". Hence, we need a further refinement here, to point out GPU capabilities more precisely.  
- [ ] Standard does not support definition of number of physical or virtual GPUs

**Comment by garloff** [comment]
> * [ ]  GPU capabilities are added to flavor name as extension. See [Complete Proposal for systematic flavor naming](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#complete-proposal-for-systematic-flavor-naming). However, the order of extensions is unclear. As there are three extensions currently, I would make sense and facilitate parsing/mapping if extensions have a dedicated order.

The order is and always has been fixed.
A sentence to make this clear is added with PR #374.

**Comment by garloff** [comment]
> [ ] There are no examples provided for flavor naming with GPU support, as is is done for CPU or [Memory](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md#examples-5)

True. We could easily add this.
Why not use `SCS-16V-64-500s_GNa-14h` as an example? (This flavor exists on one of our partner clouds.)
PCI pass-through Nvidia Ampere with 14 SMs and HBM memory. (It could also have been specially high freq, and I happen to know it's HBM memory.)
Want to submit a PR? Want me to do it?

**Comment by garloff** [comment]
>     * [ ]  [Abbreviation SUs (Streaming Multiprocessors) and EUs (Execution Units)) are used without glossary/explanation. #375](https://github.com/SovereignCloudStack/standards/issues/375)

That can easily be addressed. I just added it to the PR #374 as it fit nicely.

**Comment by garloff** [comment]
> Want to submit a PR? Want me to do it?

Added it also to PR #374.

**Comment by garloff** [comment]
>     * [ ]  According to SCS flavor naming, GPU generation, such as Ampere or Hopper for Nvidea, can be defined by adding appropriate suffix to GPU definition. IMO, placing generation is not sufficient as there is a huge performance difference between A40 and A100, both GPUs of generation "Ampere". Hence, we need a further refinement here, to point out GPU capabilities more precisely.

The number of SMs should give you an indication of how much performance to expect. Together with maybe the `h` qualifier (HBM memory). `_GNa-84` (A40) vs `_GNa-108h` (A100).

**Comment by garloff** [comment]
> Standard does not support definition of number of physical or virtual GPUs

True, that is a real limitation.

Another (and maybe more important) missing piece is that we don't specify the amount of VRAM that is available to the user, which may be a serious limitation. Does my 30b LLM model (in 4bit+ quantization, so it will require ~18GiB) fit or not?

So this would need a real extension:
`_`[I`x`][`G`/`g`]X[N][`-`M[`h`][`-`O[`h`]]]
I denoting the no of GPUs and -O the amount of memory (in GiB). `h` behind SMs/CUs/EUs would denote high freq., `h` behind O (memory) memory with bandwidth > 1TiB/s.
If we wanted to allow for heterogeneous GPUs, we could allow multiple of these options.
Obviously, you may be able to come up with a better proposal.

**Comment by anjastrunk** [comment]
> > Standard does not support definition of number of physical or virtual GPUs
> 
> True, that is a real limitation.
> 
> Another (and maybe more important) missing piece is that we don't specify the amount of VRAM that is available to the user, which may be a serious limitation. Does my 30b LLM model (in 4bit+ quantization, so it will require ~18GiB) fit or not?
> 
> So this would need a real extension: `_`[I`x`][`G`/`g`]X[N][`-`M[`h`][`-`O[`h`]]] I denoting the no of GPUs and -O the amount of memory (in GiB). `h` behind SMs/CUs/EUs would denote high freq., `h` behind O (memory) memory with bandwidth > 1TiB/s. This would be backwards compatible. If we wanted to allow for heterogeneous GPUs, we could allow multiple of these options. Obviously, you may be able to come up with a better proposal.

As I feel myself not competent enough to judge this approach, I will forward the improvement of GPU definition in SCS flavor standard to our GPU expert. This may take some time.

**Comment by garloff** [comment]
Any feedback?

**Comment by garloff** [comment]
Sidenote: The multi-GPU feature is not yet included in #780.

**Comment by garloff** [comment]
Discussion seems to have continued on https://github.com/SovereignCloudStack/standards/pull/546

**Comment by mbuechse** [comment]
Can this be closed now thanks to #780?

**Comment by mbuechse** [comment]
I'm closing this. Please open a new one with whatever's remaining.
