### ISSUE TITLE
[BUG] Standard for image metadata omits unit for "min_disk_size" and "min_ram" 

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#367]
[Image metadata standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md) refers to [useful-image-properties](https://docs.openstack.org/glance/latest//admin/useful-image-properties) for mandatory and recommended Image metadata. Two mandatory data are minimal size disk and ram- However, neither [useful-image-properties](https://docs.openstack.org/glance/latest//admin/useful-image-properties) nor [Image metadata standard](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md) defines unit of ram and disk size. IMO this information is obligatory and MUST be added to Image property standard.

**Comment by garloff** [comment]
Good catch, we are inheriting the shortcomings from upstream.
By all means, let's write this down.
min-disk is GiB, min-ram is MiB.
(Note: Disk sizes tend to be measured in GB = 10^9 and not GiB = 2^30 in the disk industry,
but OpenStack uses GiB, so we follow.)

**Comment by anjastrunk** [comment]
> Good catch, we are inheriting the shortcomings from upstream. By all means, let's write this down. min-disk is GiB, min-ram is MiB. (Note: Disk sizes tend to be measured in GB = 10^9 and not GiB = 2^30 in the disk industry, but OpenStack uses GiB, so we follow.)

Done.
