### ISSUE TITLE
[Other] add pluscloud open prod3 to healthmonitor + standards compliance check

### ISSUE THREAD

**Issue by frosty-geek** [SovereignCloudStack/standards#371]
Hi,

I've just spawned the necessary projects + users for our next productive environment aka. pluscloud open "prod3".

@garloff credentials should be in your inbox @maxwolfs mentioned that the current compliance still uses the github actions (-> I have no access to the secrets in this repo).

Ralf

**Comment by garloff** [comment]
https://health.prod1.plusserver.sovereignit.cloud:3000/d/9ltTEmlnk/openstack-health-monitor2?orgId=1&refresh=5m&var-mycmd=All&var-mymethod=All&var-mywait=All&var-mybench=All&var-mycloud=plus-prod3
has been added.
See https://github.com/SovereignCloudStack/openstack-health-monitor/pull/143.
The compliance check (SCS-compatible IaaS) will be added next ...

**Comment by mbuechse** [comment]
I think it's been dealt with.
