### ISSUE TITLE
Equip openstack-flavor-manager with the ability to set extra_specs

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#380]
For the upcoming "SCS-compatible IaaS v4", each SCS flavor MUST have the extra spec "scs:name-v2" set, among others -- see [Section "Guarantees and Properties" of scs-0103-v1](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0103-v1-standard-flavors.md#guarantees-and-properties). 

As yet, the openstack-flavor-manager does not set these properties, and this should be changed before the new standard takes effect.

**Comment by mbuechse** [comment]
While we are at it, I think openstack-flavor-manager should also be equipped with the ability to set the flavor id. @horazont

**Comment by mbuechse** [comment]
@berendt If you approve, I will create a corresponding issue in the osism repo. Then the question is who will work on it (I volunteer, of course)

**Comment by berendt** [comment]
I would be happy if you could implement it directly.

**Comment by mbuechse** [comment]
Let's use this OSISM issue: https://github.com/osism/openstack-flavor-manager/issues/19

**Comment by mbuechse** [comment]
Et voilà: https://github.com/osism/openstack-flavor-manager/pull/84 open for review
