### ISSUE TITLE
[Other] Adapt C&H test cluster to SCS Flavor Naming Standard (scs-0100)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#415]
Adapt C&H test cluster to [SCS Flavor Naming Standard (scs-0100)](https://docs-staging.scs.community/standards/scs-0100-v3-flavor-naming) and evaluate its costs. 

Todos:

- [x]  Adapt C&H test cluster to SCS standard 
- [x]  Update standard documentation with costs/cost estimation
- [x]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Cost estimation for this standard can be found [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md)

**Comment by anjastrunk** [comment]
> Cost estimation for this standard can be found [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md).
> 
> The how to and script can be found in [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md) and [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/setup.sh).

Thanks for collecting cost of making a cloud SCS compliant. We should decide, where to place this information. Implementation and Testing Notes of each standard could be a good candidate. Goal is, that providers, who want to become SCS compliant can access our lessons learned, easily.

**Comment by anjastrunk** [comment]
Furthermore, if we moved cost of making a cloud SCS compliant to its final place and our clusters (productive and test cluster) are  SCS compliant, we should close this issue.

**Comment by cah-hbaum** [comment]
Test script output:
```
    ./iaas/flavor-naming/flavor-names-openstack.py -c scs-test --mand=./iaas/scs-0100-v3-flavors.yaml:
      rc: 0
      stdout:
      - 'scs-test:'
      - '  OtherFlavorSummary:'
      - '    TotalAmount: 0'
      - '  SCSFlavorSummary:'
      - '    FlavorsWithWarnings: 0'
      - '    MandatoryFlavorsMissing: 0'
      - '    MandatoryFlavorsPresent: 0'
      - '    OptionalFlavorsValid: 28'
      - '    OptionalFlavorsWrong: 0'
      - '    TotalAmount: 28'
      - '  TotalSummary:'
      - '    Errors: 0'
      - '    Warnings: 0'
      - ''
      stderr: []
      info: 0
      warning: 0
      error: 0
      critical: 0
      result: 1
```

**Comment by cah-hbaum** [comment]
Test cluster is up and compliant, so the issue will be closed.
