### ISSUE TITLE
[Other] Adapt C&H test cluster to SCS Standard Flavors and Properties (scs-0103)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#418]
Adapt C&H test cluster to [SCS Standard Flavors and Properties (scs-0103)](https://docs-staging.scs.community/standards/scs-0103-v1-standard-flavors) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [x]  Update standard documentation with costs/cost estimation
- [x]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Test script output confirming that the cluster complies to `scs-0103-v1-standard-flavors-and-properties`:
```
    ./iaas/standard-flavors/flavors-openstack.py -c scs-test -d ./iaas/scs-0103-v1-flavors.yaml:
      rc: 0
      stdout: []
      stderr:
      - 'DEBUG: Fetching flavors from cloud ''scs-test'''
      - 'DEBUG: Checking 28 flavor specs against 28 flavors'
      - 'DEBUG: Total critical / error / info: 0 / 0 / 0'
      info: 0
      warning: 0
      error: 0
      critical: 0
      result: 1
```

**Comment by cah-hbaum** [comment]
Test cluster is up and compliant, so the issue will be closed.
