### ISSUE TITLE
[Other] Adapt C&H test cluster to SCS Standard Images (scs-0104)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#419]
Adapt images to [SCS Standard Images (scs-0104)](https://docs-staging.scs.community/standards/scs-0104-v1-standard-images) and evaluate its costs. 

Todos:

- [ ]  Make images in C&H test cluster SCS-compatible 
- [x]  Update standard documentation with costs/cost estimation
- [x]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Cost estimation for this standard can be found [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md).

The how to and script can be found in [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md) and [here](https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/setup.sh).

**Comment by cah-hbaum** [comment]
Test script output confirming that the cluster complies to `scs-0104-v1-standard-images`:
```
    ./iaas/standard-images/images-openstack.py -c scs-test -d ./iaas/scs-0104-v1-images.yaml:
      rc: 0
      stdout: []
      stderr:
      - 'DEBUG: Fetching image list from cloud ''scs-test'''
      - 'DEBUG: Images present: Debian 10, Debian 11, Debian 12, Ubuntu 20.04, Ubuntu
        22.04, ubuntu-capi-image v1.29.3'
      - 'DEBUG: Checking 6 image specs against 6 images'
      - 'DEBUG: Total critical / error / warning: 0 / 0 / 0'
      info: 0
      warning: 0
      error: 0
      critical: 0
      result: 1
```

**Comment by cah-hbaum** [comment]
Test cluster is up and compliant, so the issue will be closed.

**Comment by cah-hbaum** [comment]
We had some irregularities with the standard images setup by the `osism-image-manager`. Seems like I set the `min_ram` and `min_disk` too high. This is fixed in the next commit in accordance with the `osism-image-manager`s default values.

**Comment by berendt** [comment]
We set the min_ram & min_disk values in the image definitions itself. E.g. for Debian: https://github.com/osism/openstack-image-manager/blob/main/etc/images/debian.yml#L8-L9

Used here: https://github.com/osism/openstack-image-manager/blob/main/openstack_image_manager/main.py#L386-L394

Do we have to fix something in our image definitions?

**Comment by cah-hbaum** [comment]
> We set the min_ram & min_disk values in the image definitions itself. E.g. for Debian: https://github.com/osism/openstack-image-manager/blob/main/etc/images/debian.yml#L8-L9
> 
> Used here: https://github.com/osism/openstack-image-manager/blob/main/openstack_image_manager/main.py#L386-L394
> 
> Do we have to fix something in our image definitions?

No, don't worry. I only wrote this for documentation reasons.
I wrote my own `images.yaml` and set the values for `min_disk` and `min_ram` too high (according to internal discussions on our site).
I was told later that the `osism_image_manager` already sets default values for some distributions like e.g. Debian you pointed to https://github.com/osism/openstack-image-manager/blob/main/etc/images/debian.yml#L8-L9. So I took the values from there.

Sorry if that caused confusion.
