### ISSUE TITLE
[Other] Adapt C&H test cluster to Requirements for container registry (scs-0212)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#422]
Adapt C&H test cluster to [Requirements for container registry (scs-0212)](https://docs-staging.scs.community/standards/scs-0212-v1-requirements-for-container-registry) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [ ]  Update standard documentation with costs/cost estimation
- [ ]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
There is neither a test for this yet nor is it in the `SCS Compatible KaaS v2`, so this issue will be closed for now.
