### ISSUE TITLE
[Other] Adapt C&H test cluster to Kubernetes Nodes Anti Affinity (scs-0213)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#423]
Adapt C&H test cluster to [Kubernetes Nodes Anti Affinity (scs-0213)](https://docs-staging.scs.community/standards/scs-0213-v1-k8s-nodes-anti-affinity) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [ ]  Update standard documentation with costs/cost estimation
- [ ]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Wont be done, since this is a decision record.
