### ISSUE TITLE
[Other] Adapt C&H test cluster to Requirements for testing cluster-stacks (scs-0216)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#425]
Adapt C&H test cluster to [Requirements for testing cluster-stacks (scs-0216)](https://docs-staging.scs.community/standards/scs-0216-v1-requirements-for-testing-cluster-stacks) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [ ]  Update standard documentation with costs/cost estimation
- [ ]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
Wont be done since it is a) a decision record and b) not possible with our K8s setup based on `yaook/k8s`.
