### ISSUE TITLE
 [Other] Adapt C&H test cluster to Decisions for the Volume Type Standard (scs-0111)

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#428]
Adapt C&H test cluster to [Decisions for the Volume Type Standard (scs-0111)](https://docs-staging.scs.community/standards/scs-0111-v1-volume-type-decisions) and evaluate its costs. 

Todos:

- [ ]  Adapt C&H test cluster to SCS standard 
- [ ]  Update standard documentation with costs/cost estimation
- [ ]  Write how to and/or adaption script

**Comment by cah-hbaum** [comment]
I dont think this can be worked on yet, there is neither a test available for this nor a tool do adapt this.
Additionally, this is only a `Decision Record`, so its not binding and can't really be adopted.

**Comment by mbuechse** [comment]
It's certainly not part of any certificate scope.
