### ISSUE TITLE
scs-0103: add scs:local-storage

### ISSUE THREAD

**Issue by berendt** [SovereignCloudStack/standards#429]
To be able to identify flavors that require local storage at REGIO we use an extra spec `local_storage` (bool). This extra spec is assigned to all of our host aggregates (local_storage = True if it's a host aggregate for hosts with local storage, local_storage = False if it's a host aggregate for hosts with no local storage). I think it makes sense to standardise this extra spec as part of scs-0103 as scs: local-storage.

**Comment by berendt** [comment]
Maybe scs:disk0-type can be re-used for this purpose.

**Comment by mbuechse** [comment]
@berendt I agree that scs:disk0-type is most likely the property that is intended for this purpose.
BTW, I only stumbled upon this issue by coincidence.

**Comment by fkr** [comment]
> BTW, I only stumbled upon this issue by coincidence.

I'd recommend to configure yourself as a watcher on the issues repository. Especially with your role in the SIG Standardization that makes sense imho (since if strangers to the project submit an issue, we can't expect them to flag you personally).

**Comment by mbuechse** [comment]
@fkr totally! I will do that (but for the standards repository)

**Comment by fkr** [comment]
@mbuechse the issues repository will also hold stuff relevant for the standardization. So *please* also subscribe to this.

**Comment by mbuechse** [comment]
@berendt I have the impression that nothing needs to be done on the SCS end. Can this be closed?
