### ISSUE TITLE
General guidelines for writing test scripts

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#447]
(This is in response to <https://github.com/SovereignCloudStack/standards/issues/402>)

We want to have a document in <https://docs.scs.community/dev-docs> (to be created in <https://github.com/SovereignCloudStack/docs/tree/main/dev-docs>) that spells out general guidelines on how to interpret the language of a standards document in a test script.

As a starting point, see [this comment](https://github.com/SovereignCloudStack/standards/issues/402#issuecomment-1860939234)

First, I would expect a section that explains that certain _keywords_ are common: MUST/required, SHOULD/recommended, MAY/optional etc., and how they are to be interpreted (I think MUST is clear, but SHOULD might not be: the idea here is that a recommendation can become a requirement in the future, so better try to satisfy it -- even though the other way around is also possible, and the recommendation becomes a mere option).

Second, I would expect a section that talks about different _channels_ (ERROR, WARNING, INFO), and what keywords correspond to each channel.

Thirdly and lastly, I suppose it would be good to say that the test is _passed_ if and only if it produces no errors. Warning and information items are not relevant for this matter.

If we go ahead with the supplementary documents regarding testing (see https://github.com/SovereignCloudStack/standards/issues/437), then we should probably mention these documents as well: the general guidelines only apply if these documents do not specify anything else.

**Comment by anjastrunk** [comment]
@martinmo Please extend this guide by mentioning Python version for tests and guidelines for unit and regression tests (see #476)

**Comment by martinmo** [comment]
An initial draft was created in https://github.com/SovereignCloudStack/docs/pull/154.

**Comment by martinmo** [comment]
I'll first tackle #476 and afterwards I can amend @cah-patrickthiem's guide with further information wrt testing and Python version.
