### ISSUE TITLE
Regression and unit tests for the standards testsuite

### ISSUE THREAD

**Issue by martinmo** [SovereignCloudStack/standards#476]
As a developer of SCS conformance tests, I would like to use unit tests to be able to verify that the building blocks of my conformance test scripts work as intended, in a repeatable and automated fashion.

An example of a component that could be (unit) tested is the flavor name parser. There are already some manual testing examples that can be invoked via `Tests/iaas/flavor-naming/check-yaml.py Tests/testing`. However, they require the developer to manually compare against the expected outcome.

(Context: A recent case where such a unit test suite would have helped to spot regressions can be found in [PR #455](https://github.com/SovereignCloudStack/standards/pull/455#pullrequestreview-1890723894).)

**Comment by mbuechse** [comment]
I endorse this issue :)
We need to keep the effort bounded, but it would definitely be desirable to have a decent coverage of the most important (and most intricate) logic.
