### ISSUE TITLE
DNS recommendations: Write spec

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#48]
We have several considerations on DNS that we should capture in a design doc:
* We expect SCS IaaS providers to run their own local DNS service. In the simplest case, this would be just a resolver with a local address that would forward to upstream resolution. This resolver should be highly available (by advertising two or three servers or by being some HA setup) and be the default DNS servers in new subnet. In more sophisticated setups it would also serve the local names (neutron DNS integration) and serve local zones from designate.
* We have the domain sovereignit.cloud to resolve SCS clouds'  API/horizon/... services.
* We have the domain sovereignit.tech that can be used by users on these clouds.

This should all be documented and policies be written.

**Comment by frosty-geek** [comment]
I think the User Story should be more specific on the Use Cases:

- VM/User wants to resolv external (outside of the openstack world) dns records -> dns caches/resolver i.e. "nameserver 8.8.8.8"
- VM/User wants to resolv project/tenant internal dns names -> split horizon dns only available with the project/tenant scope
- VM/User wants to expose dns records to the outside world -> authorative dns (designate?)

I know alot of bigger providers rely on dnsdist (https://dnsdist.org/) for its dns protocol aware routing/balancing features as a "customer facing" 1st hop.

**Comment by mbuechse** [comment]
Closing this in favor of https://github.com/SovereignCloudStack/issues/issues/229
