### ISSUE TITLE
[Standard] Node distribution v2

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/standards#494]
While working on the tests for the node distribution standard [scs-0214-v1](https://github.com/SovereignCloudStack/issues/issues/477), we found a few issues that need to be addressed.

The formulation of sentences isn't quite clear in all cases, leading to problematic or unclear requirements.

The biggest issue, however, is that the standard cannot be tested as is. The test that has been devised relies on certain node labels that are set in many instances, but they need not be, so we have to amend the standard to make them required. To be specific, these labels are:

- `topology.kubernetes.io/region`,
- `topology.kubernetes.io/zone`,
- ~`kubernetes.io/hostname`~ a custom SCS label with the physical `host-id`

The last point is to be addressed in the reference implementation via https://github.com/SovereignCloudStack/issues/issues/540.

## Definition of Done:

- [x] Standard has been amended/written
- [x] Test has been amended and is working
- [x] Follow-up issue: https://github.com/SovereignCloudStack/standards/issues/639

**Comment by martinmo** [comment]
`kubernetes.io/hostname` won't be used in favor of a custom label, which is being discussed in https://github.com/SovereignCloudStack/issues/issues/540.

**Comment by cah-hbaum** [comment]
Follow-up issue: https://github.com/SovereignCloudStack/standards/issues/639
