### ISSUE TITLE
[BUG] Misleading CPU capabilites description in Flavor Name Standard

### ISSUE THREAD

**Issue by anjastrunk** [SovereignCloudStack/standards#497]
[Flavor naming standard v3](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0100-v3-flavor-naming.md) defines four exclusive CPU suffixes: C, T, V and L. Only on suffix is allowed to be used. Section "Baseline" explains meaning of suffix V and L. 

"Note that vCPU oversubscription for a V vCPU should be implemented such, that we can guarantee at least 20% of a core in >99% of the time; this can be achieved by limiting vCPU oversubscription to 5x per core (or 3x per thread when SMT/HT is enabled) or by more advanced workload management logic. Otherwise L (low performance) instead of V must be used. The >99% is measured over a month (1% is 7.2h/month)." 

IMO, this sentence is misleading. Doesn't dedicated core/thread preclude over-provisioning, as number of vCPU is limited to the number of cores/threads? If so, SMT/HT should be omitted while explaining over-provisioning as it may convey over-provisioning can be used in conjunction with SMT. 

If over-provisioning can be used in conjunction with SMT/HT, flavor naming standard must be changed. Currently, only one suffix, either C, T, V or L, is allowed. In order to distiguigh between (1) "oversubscription to 5x per core" and (2) "3x per thread", an additional suffix C or T is required.

**Comment by mbuechse** [comment]
My view is that the customer need not be concerned with the question of whether hyperthreading is enabled or not; rather, the case distinction here is supposed to lead to comparable performance in either case.

**Comment by anjastrunk** [comment]
I agree.
BTW: I prefer to define CPU's performance with more measurable/compatible metric such as Teraflops.
