### ISSUE TITLE
[Other] Yaook SCS cluster debugging

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/standards#556]
This issue contains information/problems/data about debugging and working with the Yaook SCS cluster. It will be closed, when the parent issue is closed.

See #426

**Comment by anjastrunk** [comment]
I suggest to log/fix each bug/problem in a separate issue, as done on #557 and list these issues in #426 in section "bug fixing". @cah-hbaum  What do you think?

**Comment by cah-hbaum** [comment]
No I think that would be too much overhead for no gain.
I would just log everything here in separate comments and link issues or similar things, if they're created externally.

I could've also done this in the separate issues already available for each standard, but most (or better all) bugs and problems are cluster-related and not specific to a standard.

**Comment by cah-hbaum** [comment]
08-04-2024
The virtualized Yaook cluster broke over the weekend. The exact reason isn't really known, but the problem was with multiple Openstack volumes managed by the Openstack CSI Cinder driver not being detached correctly. They would just hang around infinitely. Since our Openstack policy doesn't allow resetting volume states by users, I would have needed to involve our Operations team with this.
The problem could have been stemming from the fact, that one of the worker nodes wasn't in a ready state, so the ceph instance couldn't run on it, which probably prevented the detaching of volumes.

I tried to reset the Kubernetes cluster with `yaook/k8s`; this ejected the worker node, since the process failed because of problems with the two of the master nodes and couldn't finish rejoining the previously bad worker.
The master nodes were having problems with connecting to different debian repositories, probably because of high resource usage on the nodes.

After loosing a second master node, I decided to just reset the cluster completely, meaning deletion of all resources and a new cluster setup.

**Comment by cah-hbaum** [comment]
Had some problems with the new cluster, images couldn't seemingly be uploaded, neither from local files nor from a linked location.
This turned out to be a problem with `glance` and its secret containing the connection information to `ceph`. The secret wasn't copied correctly into the other namespace, resulting in an incorrect key distributed to `glance`, which then couldn't access ceph.

**Comment by cah-hbaum** [comment]
Problems are fixed for now (already applied the fixes on friday). The problem seemed to come from incorrectly created roles for the `neutron-ovn-operator` initially. After I fixed them manually, the `ovnagent`s seemed to be the problem. They were created without the `status` key, because it wasn't available in the CRD. I needed to manually update the CRD and fix the `ovnagent`s. After that was done, the cluster was running correctly.

**Comment by cah-hbaum** [comment]
Tried to setup the `yaook/k8s` cluster again last week, since the nodes wouldn't come out of the `NotInitialized` state. With the help of a colleague, I found out that this is probably a problem with the `OpenstackCloudController` component. Still this didn't throw any obvious errors. Im gonna investigate further this week.

**Comment by cah-hbaum** [comment]
I would close this issue, the clusters seem stable for quite some time now and other problems are reported in other issues.
