### ISSUE TITLE
Extend implementation notes by findings from #426

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#559]
Create or extend implementation notes for existing standards with the findings from #426

Transfer from https://github.com/SovereignCloudStack/standards/blob/do-not-merge/scs-compliant-yaook/Informational/adaption-costs.md

(Small edit by @cah-hbaum)

**Comment by cah-hbaum** [comment]
I'm gonna start this after I did the same thing for the KaaS layer and standards.

**Comment by cah-hbaum** [comment]
Finally created the PR last week, that only needs to be checked now.
