### ISSUE TITLE
[BUG] flavors.scs.community should keep CPU arch if non x86 in short name.

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#583]
The flavor name generator on https://flavors.scs.community/ does handily also suggest a short name for a generated flavor name that strips out some details that are not relevant for most customers.
It e.g. strips out, whether we have an intel or AMD CPU and what the CPU generation is.
For non-x86 CPUs, it strips out one detail too much though: The flavor name should encode that we have arm or riscv CPUs rather than x86-64. So we should keep it in the short name, as this does make a difference. Images will not work on both.
The standard says that a not-specified CPU vendor means generic x86-64, so we need to indicate it if we're not x86-64.

Note: This could be debated -- unlike most of the other properties, there is metadata for the architecture to ensure we don't try to boot an x86-64 image on a aarch64 flavor. But I prefer to select the non-x86 CPU architecture by explicitly saying so in chosing the flavor.

**Comment by mbuechse** [comment]
Solved with #584
