### ISSUE TITLE
[Feature Request] Link checker in pipeline

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/standards#602]
Coming from [this PR](https://github.com/SovereignCloudStack/standards/pull/581) and [this issue](https://github.com/SovereignCloudStack/standards/pull/581#discussion_r1603757250), @artificial-intelligence suggested that we should probably include a link checker to combat potential Link Rot in our standard documents.

**Comment by artificial-intelligence** [comment]
I also have implemented something similar before, you might want to check https://github.com/osism/osism.github.io/commit/3b5cf94ae366ee156bea413c769ff2a9f5734ec4 (it's similar to the above solution posted)

**Comment by martinmo** [comment]
We already have https://github.com/SovereignCloudStack/standards/blob/main/.github/workflows/link-validator.yml, which even runs on a regular schedule.

Maybe it is a configuration issue: `check-modified-files-only: 'yes'` is set unconditionally, but for the scheduled runs this doesn't make sense.

**Comment by martinmo** [comment]
Yes, if I compare a [scheduled run](https://github.com/SovereignCloudStack/standards/actions/runs/9948915507/job/27484312384) vs. a [run triggered by push](https://github.com/SovereignCloudStack/standards/actions/runs/9976396273/job/27568465173), the scheduled run is missing this

```
From https://github.com/SovereignCloudStack/standards
 * branch            main       -> FETCH_HEAD
 * [new branch]      main       -> origin/main
=========================> MARKDOWN LINK CHECK <=========================

[✔] All links are good!

=========================================================================
```

and instead just prints

```
From https://github.com/SovereignCloudStack/standards
 * branch            main       -> FETCH_HEAD
All good!
```

which makes me think nothing is checked at all in this case.

(Unfortunately it doesn't show more details, e.g., number of files checked.)
