### ISSUE TITLE
[Feature Request] Storage flavor naming scheme is needed

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/standards#63]
The [flavor naming scheme]( ) currently covers compute. In Team Ops meeting on April 21st it was debated, as part of the refinement of the OpenStack Flavor Manager, that a naming scheme for storage is needed.

**Comment by mbuechse** [comment]
@fkr Is this still relevant? What specifically is needed (besides what the standard offers)?

**Comment by mbuechse** [comment]
Closed as unclear
