### ISSUE TITLE
[BUG] SCS 0104-v1 is confusing, since the required image(s) can't easily be seen

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/standards#635]
The subject says its all. Neither @garloff nor I were able to see it immediately which image is required.

**Comment by mbuechse** [comment]
Closed as duplicate of #534. We're on the case already.

**Comment by fkr** [comment]
thanks @mbuechse for spotting this. - this came up in a meeting that @garloff and I had with colleagues from Cleura and I wanted to make sure to add the issue and did not do any further research while in the meeting.
