### ISSUE TITLE
[Feature Request] KaaS conformance tests with other providers/implementations

### ISSUE THREAD

**Issue by martinmo** [SovereignCloudStack/standards#649]
At the moment, conformance tests run as part of our Zuul E2E tests and only for the reference implementation. Other implementations and clouds should be included, e.g., Gardener on REGIO.cloud.

CC @tonifinger

**Comment by mxmxchere** [comment]
Sounds like a perfect use case for the moin-cluster. The cluster comes pre-deployed with a few (currently one, planned are more) clusterstacks. You can login via oidc. Some namespaces are pre-equipped with credentials for gx-scs. You can find infos [here](https://github.com/SovereignCloudStack/moin-cluster-config?tab=readme-ov-file#usage). To access the predeployed namespaces you have to be member of the team [moin-cluster-all-playgrounds](https://github.com/SovereignCloudStack/github-manager/blob/main/orgs/SovereignCloudStack/data.yaml#L287). Btw @jschoone will host a little intro presentation on how to use the cluster in tomorrows community-call. A bulk-PR to add people to the all-playgrounds-team is also planned.

**Comment by martinmo** [comment]
@mxmxchere I am already part of the [moin-cluster-playground1](https://github.com/SovereignCloudStack/github-manager/blob/e9d82e6763ff1cae4a902c8ef82c4ad9ed6fa5ca/orgs/SovereignCloudStack/data.yaml#L290-L301) team, but with the kubeconfig described in the [usage](https://github.com/SovereignCloudStack/moin-cluster-config?tab=readme-ov-file#usage) I can't list the pods:

```
$ kubectl get pods
Error from server (Forbidden): pods is forbidden: User "oidc:martinmo" cannot list resource "pods" in API group "" in the namespace "default"
```

I also tried namespaces `playground1` and `kaas-playground1` with the same result. OIDC login via GitHub worked as expected, however.

**Comment by martinmo** [comment]
Infos from today's Container Call:

Currently, there is some restructuring going on and the `moin-cluster-playground1` has no access anymore. Instead, it is planned to create the team as outlined [above](https://github.com/SovereignCloudStack/standards/issues/649#issuecomment-2191823419). This will be announced in a lightning talk today.

For getting access to Gardener based clusters we can use [Plusserver PSKE](https://docs.plusserver.com/en/container/managed-kubernetes/documentation/clusterinteraction/cluster-provisioning/) or regiocloud. Credentials can be obtained from `@joshmue` and `@mxmxchere`, respectively.

**Comment by mbuechse** [comment]
Yes, please! Go ahead.

**Comment by tonifinger** [comment]
This Issue can be closed. The basic concept to enable other providers to use the scs kaas conformance tests got introduced with #753.
Further work regarding specific provider implementations will be addressed by:
- #831 
- #800 
- #794
