### ISSUE TITLE
Increase granularity of badges or certification

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#660]
It has become apparent already that the certificate scope `SCS-compatible IaaS` might cover a lot of aspects, and some of those aspects might not be applicable to every CSP (for instance, private clouds may not offer public IP addresses), while other aspects might be relevant for promotional purposes and should be made visible accordingly (such as "overachievement" in matters of encryption and security).

This situation calls for

1. either more fine-grained badges, making certain aspects more visible, which means more modular/structured scopes,
2. or more fine-grained certification (more and smaller scopes),
3. or both.

In addition, we might want to make badges more gradual, that is, that we not only say "passed" or "failed" (in whatever granular manner), but we might want to say "x % passed", so that the badge doesn't turn red immediately just because one test fails. Note that we should **distinguish granularity and gradation** and deal with them separately.

This issue is meant as a place for discussion, for collecting desiderata and use-cases and so on.

**Comment by garloff** [comment]
Displaying a fine-grade status easily gets confusing, so we are limited in what we can transport.

One possibility would be to stick to a green (100+% passing) / red (<100%) scheme on the overview page and have additional details if people drill down.

The drill down view then would show a lot more information:
* Pass rate (with a gradual color change)
* Bonus tests passed (recommendations)
* Failed mandatory tests
* And even a note section where the SIG can agree on having a config note with wording that would explain the results (and maybe in some cases excuse a provider)

There are certainly other ways. But somehow, we need to make sure that a 90% pass rate does not get brushed away with good enough. Because it means that users can not rely on their application working ...

**Comment by mbuechse** [comment]
One thing I forgot to mention in the main description: these "aspects" are orthogonal to the standards, in other words, they comprise recommendations and requirements that may be scattered over multiple standards, as is the case with encryption and security. It may thus be advisable to introduce more structure into the standards, more precisely, to use numbered lists so that each recommendation and each requirement has a unique number and can be referenced. A standard, then, could be viewed as merely a catalogue (maybe even hierarchically organized) of these recommendations and requirements, and a certificate scope, which is basically a collection of standards, could be viewed as simply a larger catalogue (which is particularly obvious with the hierarchical organization). Then, the test scripts would have to produce and log a result for each of these numbers. With this information, it should be possible to aggregate results per aspect.

**Comment by mbuechse** [comment]
In the draft PR attached to this issue, I have prepared a sketch of what I think could be a viable solution. It is based on the following changes:

- for each standard, we define a list of _test items_ (called "checks" in the yaml mainly for historic reasons)
- each such item carries a list of _tags_
- each test script has to produce a line `item name: PASS` or `item name: FAIL` for each item (except it can't because of some exception, then the result cannot be recorded, and it it counts as though the test never ran)
- the certificate scope may define multiple _targets_, where the target named "main" is what determines the overall badge
- each target is a collection of test items, and these items are collected using the tags; here the "main" target collects all items that have the tag "mandatory", but we could add more targets that collect other items (and these targets can be overlapping)
- so far, with one exception, I only created one mandatory test item for each standard (for a transition period)
- see the entropy standard for the exceptionwhere I split the test up into multiple items, some of them non-mandatory

**Comment by mbuechse** [comment]
Important insights from today's SIG Std/Cert:

- good docs for developers of test scripts necessary
- good explanation for CSPs (blog post), too
- and the main check script should output a final verdict (stating any missing test items)
