### ISSUE TITLE
[BUG] absence of rngd is not reported as error

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#673]
It's a mismatch between

a) the standard and the testing guide on the one hand and
b) the test script on the other.

The [standard](https://docs.scs.community/standards/scs-0101-v1-entropy#images) clearly states:

> The daemon rngd must be installed (usually from rng-tools or rng-utils).

The [testing guide](https://docs.scs.community/standards/scs-0101-w1-entropy-implementation-testing#errors) concurs:

> [report error if] the service rngd is not running,

However, [the script](https://github.com/SovereignCloudStack/standards/blob/main/Tests/iaas/entropy/entropy-check.py#L164) only issues a warning:

> `logger.warning(f"VM '{image.name}' doesn't provide the recommended service rngd")`

Options:

* change the script -- but then multiple test subjects will no longer pass the tests for SCS-compatible IaaS v4;
* change the standard.

Opinions?

**Comment by berendt** [comment]
I think an error is okay at this point. The cluster to be certified must provide images that can pass the intended tests. It is the operator's responsibility to provide an image that fulfils the requirements.

**Comment by mbuechse** [comment]
> It is the operator's responsibility to provide an image that fulfils the requirements.

At the same time, we want providers to use the original images wherever possible. See https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Tests/iaas/scs-0104-v1-images.yaml

**Comment by berendt** [comment]
> > It is the operator's responsibility to provide an image that fulfils the requirements.
> 
> At the same time, we want providers to use the original images wherever possible. See https://raw.githubusercontent.com/SovereignCloudStack/standards/main/Tests/iaas/scs-0104-v1-images.yaml

Yes. But I think at least in the Ubuntu 22.04 image the required packages are included:

```
rng-tools5 - Daemon to use a Hardware TRNG
```

**Comment by mbuechse** [comment]
Close this in favor of https://github.com/SovereignCloudStack/standards/issues/674
