### ISSUE TITLE
[Feature Request] CNCF conformance tests

### ISSUE THREAD

**Issue by tonifinger** [SovereignCloudStack/standards#709]
This issue was created to provide a discussion ground for possible future standards. It is derived from SovereignCloudStack/issues#181 and one of the points not assigned any issue yet.

As a cloud service provider, I want my KaaS to comply with the [Certified Kubernetes Software Conformance ](https://www.cncf.io/training/certification/software-conformance/)
Here we discuss how the "Certified Kubernetes Software Conformance" can be utilized.

## Needs:

* #710

## Definition of Done:

- [ ] Perform CNCF conformance tests using sonobuoy #819
- [ ] Collecting the results and converting them into an output that can be interpreted by the SCS

**Comment by mbuechse** [comment]
@tonifinger I created https://github.com/SovereignCloudStack/standards/issues/710 for the plugin topic.

**Comment by mbuechse** [comment]
This hss been done with the inclusion of Sonobuoy.
