### ISSUE TITLE
 make compliance test for scs-0115-v1: Default Rules for Security Groups downward compatible

### ISSUE THREAD

**Issue by fraugabel** [SovereignCloudStack/standards#746]
For Yaook-based Openstack, that consists neather of deprecated or latest versions of components the compliance test for Default Rules for Security Groups should still be usable:
* if the current test fails (requesting https://neutron.l1a.cloudandheat.com:443/v2.0/default-security-group-rules), there should be an alternative test that 
1. creates a new security group to check whether default security group rules are automatically applied
1. therefor checks for egress rules for IPv4 and IPv6 allowing all traffic
1. and checks for ingress rules IPv4 and IPv6 blocking all traffic
1. then deletes security group again

Note:
requesting default-security-group-rules is available for yaook 2023.2 and later

**Comment by fraugabel** [comment]
added alternative test, because the current test only works for the latest versions of the network and compute services, though older versions are not depricated yet

**Comment by fraugabel** [comment]
PR: https://github.com/SovereignCloudStack/standards/pull/748

**Comment by mbuechse** [comment]
Please only close when the PR is merged. Github can do that automatically – just link the two.
