### ISSUE TITLE
[Feature Request] Compliance monitor colors

### ISSUE THREAD

**Issue by garloff** [SovereignCloudStack/standards#801]
We currently assign green if a cloud passes the currently effective version of a certification scope, red if it only passes deprecated versions and no color is nothing is passed.
Green is fine, but I would revert the colorization of the latter:
* Red if NOTHING passes
* No color (or amber) if only old versions pass.

**Comment by mbuechse** [comment]
I think we assign red in both cases. Do you have a screenshot?

**Comment by garloff** [comment]
My bad. I should have checked and not worked from memory.
Sorry for the noise!
Question that remains:
- Should we differentiate, color-wise, between not passing at all and passing an outdated (deprecated) version?

**Comment by mbuechse** [comment]
@garloff I think that is a good idea. It might require some refactoring. I will try to fit that in; we can sort out the details later.
