### ISSUE TITLE
Stabilize standards for SCS-compatible IaaS v5

### ISSUE THREAD

**Issue by mbuechse** [SovereignCloudStack/standards#807]
See #787 for list of standards -- go before Team IaaS with the respective PRs:

- scs-0114-v1: #808 
- scs-0115-v1: #809
- scs-0116-v1: #810
- scs-0117-v1: #752
- scs-0121-v1: #811
- scs-0302-v1: #586

While we are at it, also make sure to approve

- https://github.com/SovereignCloudStack/standards/pull/812

**Comment by anjastrunk** [comment]
All tasks are done. I guess, we can close this issue. @mbuechse What do you think?

**Comment by mbuechse** [comment]
Yes, this is done.
