### ISSUE TITLE
Create overview of standards

### ISSUE THREAD

**Issue by itrich** [SovereignCloudStack/standards#86]
As inspired by @jklippel, we should provide an overview of our standards and their current state (release version, draft, etc.)

We discussed today during SIG Standardization that we'll add a table to the root `README.MD` and link to the various documents.

**Comment by itrich** [comment]
Should this be automated (and entailing the danger of over-engineering) or edited manually?

**Comment by frosty-geek** [comment]
Since gaia-x launched their portal maybe something in-line with https://docs.gaia-x.eu/framework/ would be beneficial

**Comment by fkr** [comment]
This does look interesting and could be worthwhile to look at in depth. thanks @***@***.*** - +49-172-1717311GPG/PGP: 824CE0F0 /  2082 651E 5104 F989 4D18  BB2E 0B26On 24. Sep 2022, at 17:04, Ralf Heiringhoff ***@***.***> wrote:﻿
Since gaia-x launched their portal maybe something in-line with https://docs.gaia-x.eu/framework/ would be beneficial

**Comment by itrich** [comment]
See #148. I'm sure that we can easily create a front-end similar to https://docs.gaia-x.eu/framework/.

**Comment by itrich** [comment]
There will be a new re-designed overview of the Gaia-X Framework, which looks really great: https://docs.gaia-x.eu/framework/beta/

**Comment by maxwolfs** [comment]
The beta link responds with a 404. Is the beta overview @itrich has provided now merged into the main overview: https://docs.gaia-x.eu/framework ? If so, i very much like the approach of it!

**Comment by itrich** [comment]
I'll close this as we've already have a machine-readable overview with SCS-0003. The interactive web frontend will be discussed and tracked with https://github.com/SovereignCloudStack/docs-page/issues/41
